<a href="https://colab.research.google.com/github/AlejandroSenabre/MTPL-Insurance-Pricing-GLM-vs-ML/blob/main/notebooks/eda_and_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Upload data from drive
from google.colab import drive
import pandas as pd
drive.mount('/content/drive')
drive_path = '/content/drive/My Drive/Programacion/Actuary/freMTPL2/'
df_freq = pd.read_csv(drive_path + 'freMTPL2freq.csv')  #Frequency
df_sev = pd.read_csv(drive_path + 'freMTPL2sev.csv')    #Severity

Mounted at /content/drive

In [24]:
print("Severity data")
display(df_sev.head(2))
print("\nSeverity data")
display(df_freq.head(5))

Severity data

     IDpol  ClaimAmount
0     1552       995.20
1  1010996      1128.12

Severity data

,IDpol,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Area,Density,Region
0,1.0,1,0.10,5,0,55,50,B12,Regular,D,1217,Rhone-Alpes
1,3.0,1,0.77,5,0,55,50,B12,Regular,D,1217,Rhone-Alpes
2,5.0,1,0.75,6,2,52,50,B12,Diesel,B,54,Picardie
3,10.0,1,0.09,7,0,46,50,B12,Diesel,B,76,Aquitaine
4,11.0,1,0.84,7,0,46,50,B12,Diesel,B,76,Aquitaine

In [11]:
# Display a summary of the 'ClaimAmount' variable, formatted in euros.
print(df_sev['ClaimAmount'].describe().apply(lambda x: f"€{x:,.2f}"))

count       €26,639.00
mean         €2,278.54
std         €29,297.48
min              €1.00
25%            €686.81
50%          €1,172.00
75%          €1,228.08
max      €4,075,400.56
Name: ClaimAmount, dtype: object